#+TITLE: Term Prediction on Text Notes

This project is an assortment of tools used for term prediction in
text notes. It was originally used specifically for term prediction
on clinical notes. 

* Dependencies
python3, nltk, numpy, spacy, pandas, scikit-learn, empath, spacy, scispacy,
liac-arff, matplotlib, wordcloud, scispacy
** Optional Dependencies
Weka, Java, python-weka-wrapper3

* Installation
First, clone the repository:
#+BEGIN_SRC shell
  git clone https://github.com/kflasch/term-predict.git
#+END_SRC
Next, install the dependencies. It is suggested to setup a venv
(Python virtual environment) or equivalent:
#+BEGIN_SRC shell
  python -m venv venv/term-predict
  source venv/term-predict/bin/activate
#+END_SRC
and then use pip to install them. You can install the dependencies
via the provided requirements.txt file:
#+BEGIN_SRC shell
  pip install -r requirements.txt
#+END_SRC
Or you can install the dependencies individually:
#+BEGIN_SRC shell
  pip install nltk
  pip install numpy
  pip install pandas
  pip install scikit-learn
  pip install liac-arff
  pip install matplotlib
  pip install wordcloud
  pip install empath
  pip install spacy
  pip install scispacy

  # Optionally, for Weka (requires Weka and Java to be installed separately):
  pip install javabridge
  pip install python-weka-wrapper3
#+END_SRC

Download data for NLTK as described at [[https://www.nltk.org/data.html][Installing NLTK Data]]. An easy way
to do this (which typically downloads the data to ~/nltk_data) is:
#+BEGIN_SRC shell
  python -m nltk.downloader all
#+END_SRC

Finally, install at least one of the scispaCy models for NER. You may want to confirm
these URLs, find updates to them, or find additional models at: [[https://github.com/allenai/scispacy]]
#+BEGIN_SRC shell
  pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_sm-0.4.0.tar.gz
  pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz
  pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_scibert-0.4.0.tar.gz
  pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_ner_bionlp13cg_md-0.4.0.tar.gz
#+END_SRC

* Usage
Most programs can be run with -h to see their options.
** config.py
Configuration file for the various tools to define datafiles, options,
etc.
** term_predict.py
The main program to run prediction and cross-validations across
different classifiers.
** create_datafiles.py
Creates pandas dataframes (as pkl files) and arff files form CSV notes
to be used by term_predict.py. Also creates templates to be used for
manual ratings.
** notes_analyzer.py
Show information about CSV notes, ratings information, generate wordclouds.
** empath_helper.py
Create categories to be used by Empath.
** weka_runner.py
Used to run Weka on datafiles with python-weka-wrapper3.
** misc
The misc directory contains a few unused files that may be of some
interest, relating to using other libraries.
